baseurl: /news-arabspatial
permalink: pretty
markdown: rdiscount
prose:
  rooturl: '_posts'
  siteurl: 'http://rrlara.github.io/news-arabspatial/'
  relativeLinks: 'http://rrlara.github.io/news-arabspatial/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image URL"
          value: ""
      - name: "youtube_url"
        field:
          element: "text"
          label: "Youtube Video ID"
          value: ""
          placeholder: "1234456789"
      - name: "vimeo_url"
        field:
          element: "text"
          label: "Vimeo Video ID"
          value: ""
          placeholder: "12345678"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          alterable: "true"
          placeholder: "Choose Tags"
          options:
            - name: "Work"
              value: "work"
            - name: "Services"
              value: "services"
            - name: "About Us"
              value: "about us"
            - name: "Careers"
              value: "careers"
      - name: "summary"
        field:
          element: "text"
          label: "Summary"
          value: ""
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
